### ISSUE TITLE
Wrong use of @Mod.InstanceFactory

### ISSUE THREAD

**Issue by liach** [3TUSK/BiliLiveMonitor#1]
https://github.com/MinecraftForge/MinecraftForge/blob/babe0c2d539cd99c27233ea42962d5df0333d87e/src/main/java/net/minecraftforge/fml/common/FMLModContainer.java#L402

`@Mod.InstanceFactory` can be only used on static methods. This method is not static in the latest commit:
https://github.com/3TUSK/BiliLiveMonitor/blob/66ec27a1d70babb8e23772481388cb8f8345f482/src/main/java/info/tritusk/projectbilistream/BiliStreamMod.java#L16

And you can also remove the `@Mod.Instance` annotation from the the `INSTANCE` field.

From
```java
@Mod.Instance(MODID)
private static BiliStreamMod INSTANCE;
```
to
```java
private static final BiliStreamMod INSTANCE = new BiliStreamMod();
```

**Comment by 3TUSK** [comment]
LEGACY REMAIN

**Comment by liach** [comment]
Do you mean this has been abandoned?

**Comment by 3TUSK** [comment]
that should have been removed when we decided to switch to `Mod.Instance`

**Comment by liach** [comment]
`@Mod.Instance` is less safe than `@Mod.InstanceFactory`.

**Comment by 3TUSK** [comment]
but it does not matter here
